spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    hikari:
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: db.migration
server:
  port: ${AUTHORIZATION_SERVER_PORT:8080}
